<?php

// $Id: aiaraldea_vimeo.module,v 1.1.2.1 2011/01/31 14:28:33 wojtha Exp $

/**
 * @file
 * Adds a Vimeo feed processor to the Feeds module.
 */

/**
 * Implements ctools_plugin_api().
 */
function aiaraldea_vimeo_ctools_plugin_api($owner, $api) {
    if ($owner == 'feeds' && $api == 'plugins') {
        return array('version' => 1);
    }
}

/**
 * Implementation of hook_feeds_plugins().
 */
function aiaraldea_vimeo_feeds_plugins() {
    $info = array();
    $info['AiaraldeaVimeoParser'] = array(
        'name' => 'Aiaraldea Vimeo parser',
        'description' => 'Parse Vimeo feeds.',
        'help' => 'Use PHP SimpleXML parser to parse Vimeo feeds.',
        'handler' => array(
            'parent' => 'FeedsParser',
            'class' => 'AiaraldeaVimeoParser',
            'file' => 'AiaraldeaVimeoParser.inc',
            'path' => drupal_get_path('module', 'aiaraldea_vimeo'),
        ),
    );
    return $info;
}

