<?php

/**
 * Implementation of hook_uuid_features_default_content().
 */
function aiaraldea_azala_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
    'type' => 'page',
    'language' => 'eu',
    'uid' => '1',
    'status' => '1',
    'created' => '1338500591',
    'changed' => '1338500696',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'revision_uid' => '1',
    'title' => 'Plaza irekia',
    'body' => '<h3>Zer da Plaza atala</h3>
  <p><strong></strong>Plaza irekia <a href="http://www.aiaraldea.com/">www.aiaraldea.com</a> web-guneko erabiltzaileen parte-hartzea sustatzeko tresna da, zu zeu elkarrizketatzaile bilakatzeko modu bat.</p>
  <p>3-4 astetik behin irekiko dugu elkarrizketa parte hartzaileak egiteko aukera. Modu honetan, plazara gonbidatutako pertsonari interesa pizten dizun hori galdetu ahalko diozu.</p>
  <h3>Nola parte-hartu?</h3>
  <p><strong></strong>Prozedura oso erreza da: astearteetan iragarriko da plaza irekian elkarrizketagai izango den pertsona. Igandea bitarte, zuen galderak  <em><a href="mailto://plaza@aiaraldea.com">plaza@aiaraldea.com</a></em> helbidera bidaltzeko epea izango duzue. Hurrengo asteko asteazkenean argitaratuko da elkarrizketa partehartzailea.</p>
  <p>Galderarekin batera, egile gisa zein izen agertzea nahi duzuen adierazi beharko duzue mezuan.</p>
  <h3><span style="font-weight: normal;">Parte-hartzeko arauak</span></h3>
  <ul>
  <li> Modu 	zuzen edo traketsean izan, euskaraz idatzitako galderak onartuko 	dira soilik. </li>
  <li> Saiatu 	zure galderak izen-abizenekin sinatzen. Indar handiagoa du.</li>
  <li>Galdera 	errepikakorrak jasoz gero, bat bakarrean erredaktatzeko hautua egin 	dezake Aiaraldea Komunikazio Leihoak.</li>
  <li>Irainak, 	debaldeko salaketak eta difamazioak onargaitzak dira.</li>
  <li>Arauok 	hausten badira, Aiaraldea Komunikazio Leihoak galdera 	elkarrizketatuari egin edo ez erabakiko du.</li>
  <li>Azkenik, 	errespetuz eta zentzuz jokatzeko deia luzatzen dizuegu!</li>
  </ul>',
    'teaser' => '<h3>Zer da Plaza atala</h3>
  <p><strong></strong>Plaza irekia <a href="http://www.aiaraldea.com/">www.aiaraldea.com</a> web-guneko erabiltzaileen parte-hartzea sustatzeko tresna da, zu zeu elkarrizketatzaile bilakatzeko modu bat.</p>
  <p>3-4 astetik behin irekiko dugu elkarrizketa parte hartzaileak egiteko aukera. Modu honetan, plazara gonbidatutako pertsonari interesa pizten dizun hori galdetu ahalko diozu.</p>',
    'log' => '',
    'revision_timestamp' => '1338500696',
    'format' => '3',
    'name' => 'mairua',
    'picture' => '',
    'data' => 'a:8:{s:15:"l10n_client_key";s:36:"744:2ffba450fcda45be3e8c73f54a5a3076";s:13:"form_build_id";s:37:"form-e644dcde8b9000c469924c575e64d639";s:18:"admin_compact_mode";b:1;s:10:"blog_theme";s:3:"sky";s:5:"Title";s:14:"Druiden txokoa";s:11:"Description";s:35:"Aiaraldeko web garatzailearen bloga";s:6:"format";s:1:"1";s:11:"remember_me";i:1;}',
    'path' => 'elkarrizketak/plaza-irekia',
    'last_comment_timestamp' => '1338500591',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'radioactivity' => array(
      'energy' => array(
        '1' => 6,
        '2' => 6,
      ),
    ),
    'uuid' => 'c0fdc126-ab6b-11e1-a1f8-dc0ea1167747',
    'revision_uuid' => 'cc8238a8-ab69-11e1-a1f8-dc0ea1167747',
    'pathauto_perform_alias' => FALSE,
    'date' => '2012-05-31 23:43:11 +0200',
  );
  return $nodes;
}
