<?php

/**
 * Implementation of hook_uuid_features_default_content().
 */
function aiaraldea_azala_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
    'type' => 'page',
    'language' => 'eu',
    'uid' => '0',
    'status' => '1',
    'created' => '1338500591',
    'changed' => '1340746540',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'revision_uid' => '0',
    'title' => 'Plaza irekia',
    'body' => '<h3>Zer da Plaza atala</h3>
    <p><strong></strong>Plaza irekia <a href="http://www.aiaraldea.com/">www.aiaraldea.com</a> web-guneko erabiltzaileen parte-hartzea sustatzeko tresna da, zu zeu elkarrizketatzaile bilakatzeko modu bat.</p>
    <p>3-4 astetik behin irekiko dugu elkarrizketa parte hartzaileak egiteko aukera. Modu honetan, plazara gonbidatutako pertsonari interesa pizten dizun hori galdetu ahalko diozu.</p>
    <h3>Nola parte-hartu?</h3>
    <p><strong></strong>Prozedura oso erreza da: astearteetan iragarriko da plaza irekian elkarrizketagai izango den pertsona. Igandea bitarte, zuen galderak  <em><a href="mailto://plaza@aiaraldea.com">plaza@aiaraldea.com</a></em> helbidera bidaltzeko epea izango duzue. Hurrengo asteko asteazkenean argitaratuko da elkarrizketa partehartzailea.</p>
    <p>Galderarekin batera, egile gisa zein izen agertzea nahi duzuen adierazi beharko duzue mezuan.</p>
    <h3><span style="font-weight: normal;">Parte-hartzeko arauak</span></h3>
    <ul>
    <li> Modu 	zuzen edo traketsean izan, euskaraz idatzitako galderak onartuko 	dira soilik. </li>
    <li> Saiatu 	zure galderak izen-abizenekin sinatzen. Indar handiagoa du.</li>
    <li>Galdera 	errepikakorrak jasoz gero, bat bakarrean erredaktatzeko hautua egin 	dezake Aiaraldea Komunikazio Leihoak.</li>
    <li>Irainak, 	debaldeko salaketak eta difamazioak onargaitzak dira.</li>
    <li>Arauok 	hausten badira, Aiaraldea Komunikazio Leihoak galdera 	elkarrizketatuari egin edo ez erabakiko du.</li>
    <li>Azkenik, 	errespetuz eta zentzuz jokatzeko deia luzatzen dizuegu!</li>
    </ul>',
    'teaser' => '<h3>Zer da Plaza atala</h3>
    <p><strong></strong>Plaza irekia <a href="http://www.aiaraldea.com/">www.aiaraldea.com</a> web-guneko erabiltzaileen parte-hartzea sustatzeko tresna da, zu zeu elkarrizketatzaile bilakatzeko modu bat.</p>
    <p>3-4 astetik behin irekiko dugu elkarrizketa parte hartzaileak egiteko aukera. Modu honetan, plazara gonbidatutako pertsonari interesa pizten dizun hori galdetu ahalko diozu.</p>',
    'log' => '',
    'revision_timestamp' => '1340746540',
    'format' => '3',
    'name' => '',
    'picture' => '',
    'data' => NULL,
    'path' => 'elkarrizketak/plaza-irekia',
    'last_comment_timestamp' => '1339621132',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'radioactivity' => array(),
    'uuid' => 'c0fdc126-ab6b-11e1-a1f8-dc0ea1167747',
    'revision_uuid' => '95352622-b59a-11e1-9ba4-fefd6d4accf1',
    'pathauto_perform_alias' => FALSE,
    'date' => '2012-05-31 22:43:11 +0100',
  );
  return $nodes;
}
