<?php 
// $Id: aiaraldea_youtube.module,v 1.1.2.1 2011/01/31 14:28:33 wojtha Exp $

/**
 * @file
 * Adds a Youtube feed processor to the Feeds module.
 */

/**
 * Implementation of hook_feeds_plugins().
 */
function aiaraldea_youtube_feeds_plugins() {
  $info = array();
  $info['AiaraldeaYoutubeParser'] = array(
    'name' => 'Aiaraldea Youtube parser',
    'description' => 'Parse Youtube feeds.',
    'help' => 'Use PHP SimpleXML parser to parse Youtube feeds.',
    'handler' => array(
      'parent' => 'FeedsParser',
      'class' => 'AiaraldeaYoutubeParser',
      'file' => 'AiaraldeaYoutubeParser.inc',
      'path' => drupal_get_path('module', 'aiaraldea_youtube'),
    ),
  );
  return $info;
}
