<?php
/**
* Implementation of hook_field_formatter_info().
*/

function simple_jplayer_field_formatter_info() {
  $formatters = array();
  $formatters['mini_downloadable'] = array(
    'label' => t('Miniaudioplayer with download'),
    'field types' => array('filefield'),
    'description' => t('Displays a miniaudioplayer with download.'),
  );
  $formatters['mini'] = array(
    'label' => t('Miniaudioplayer'),
    'field types' => array('filefield'),
    'description' => t('Displays a miniaudioplayer.'),
  );
  $formatters['mini_for_link'] = array(
    'label' => t('Miniaudioplayer'),
    'field types' => array('link'),
    'description' => t('Displays a miniaudioplayer.'),
  );
  $formatters['mini_for_link_downloadable'] = array(
    'label' => t('Miniaudioplayer with download'),
    'field types' => array('link'),
    'description' => t('Displays a miniaudioplayer with download.'),
  );
  return $formatters;
}

/**
 * Implementation of hook_theme().
 */
function simple_jplayer_theme() {
  $themes = array();
  $themes['simple_jplayer_formatter_mini'] = array(
    'arguments' => array('element' => NULL),
    'function' => 'theme_simple_jplayer_formatter_mini',
  );
  $themes['simple_jplayer_formatter_mini_downloadable'] = array(
    'arguments' => array('element' => NULL),
    'function' => 'theme_simple_jplayer_formatter_mini_downloadable',
  );
  $themes['simple_jplayer_formatter_mini_for_link'] = array(
    'arguments' => array('element' => NULL),
    'function' => 'theme_simple_jplayer_formatter_link_mini',
  );
  $themes['simple_jplayer_formatter_mini_for_link_downloadable'] = array(
    'arguments' => array('element' => NULL),
    'function' => 'theme_simple_jplayer_formatter_link_mini_downloadable',
  );
  return $themes;
}

function theme_simple_jplayer_formatter_mini_downloadable($element) {
  return _theme_simple_jplayer_formatter_mini($element, true);
}
function theme_simple_jplayer_formatter_mini($element) {
  return _theme_simple_jplayer_formatter_mini($element, false);
}

function _theme_simple_jplayer_formatter_mini($element, $downloadable = false) {
  $output = '';
  
  $item = $element['#item'];
  if($item['list'] == "0") {
    // Isn't listed so bail now
    return;
  }
  
  if(isset($item['data']['description']) && is_array($item['data'])) {
    //Data straight from node isn't serialized
    $description = $item['data']['description'];
  }
  else if(isset($item['data']['description']) && is_array(unserialize($item['data']))){
    //Data from a View is on the other hand
    $bits = unserialize($item['data']);
    $description = $bits['description'];
  } else {
    $description = $item['filename'];
  }
  if ($downloadable) {
    $properties = "{width:'100%',volume:10,showVolumeLevel:false,showRew:false,skin:'aiaraldea',downloadable:true}";
  } else {
    $properties = "{width:'100%',volume:10,showVolumeLevel:false,showRew:false,skin:'aiaraldea'}";
  }
//   var_dump($element);
$fid = $element['#item']['fid'];
$delta = $element['#item']['#delta'];
//   var_dump($fid);
$url = file_create_url($item['filepath']);
  $output .= "<a id=\"player_".$fid."_".$delta."\" class=\"audio-jp $properties\" href=\"$url\">$description</a>";
  $module_path = drupal_get_path('module', 'simple_jplayer');;
  if ($path = libraries_get_path("jquery.mb.miniAudioPlayer")) {
    drupal_add_js($path . '/inc/jquery.jplayer.min.js');
    drupal_add_js($path . '/inc/jquery.mb.miniPlayer.js');
    drupal_add_js($module_path . '/simple_player.js');
    drupal_add_css($path . '/css/miniplayer.css');
  }

  return $output;
}

function theme_simple_jplayer_formatter_link_mini_downloadable($element) {
  return _theme_simple_jplayer_formatter_link_mini($element, true);
}
function theme_simple_jplayer_formatter_link_mini($element) {
  return _theme_simple_jplayer_formatter_link_mini($element, false);
}

function _theme_simple_jplayer_formatter_link_mini($element, $downloadable = false) {
  $output = '';
  
  $item = $element['#item'];
  if($item['list'] == "0") {
    // Isn't listed so bail now
    return;
  }
  if ($downloadable) {
    $properties = "{width:'100%',volume:10,showVolumeLevel:false,showRew:false,skin:'aiaraldea',downloadable:true}";
  } else {
    $properties = "{width:'100%',volume:10,showVolumeLevel:false,showRew:false,skin:'aiaraldea'}";
  }
  $fid = $element['#node']->nid;
  $delta = $element['#item']['#delta'];
  $url=$item['url'];
//   var_dump($fid);
  $output .= "<a id=\"player_$fid"."_$delta\" class=\"audio-jp $properties\" href=\"$url\">$url</a>";
  $module_path = drupal_get_path('module', 'simple_jplayer');
  if ($path = libraries_get_path("jquery.mb.miniAudioPlayer")) {
    drupal_add_js($path . '/inc/jquery.jplayer.min.js');
    drupal_add_js($path . '/inc/jquery.mb.miniPlayer.js');
    drupal_add_js($module_path . '/simple_player.js');
    drupal_add_css($path . '/css/miniplayer.css');
  }

  return $output;
}
